#ifndef JOBS_MANAGER_JOB_ENUM_H
#define JOBS_MANAGER_JOB_ENUM_H

enum JobType {
   JOB_TYPE_BATCH,
   JOB_TYPE_SERVICE,
   JOB_TYPE_CRON,
}; 

enum JobRawPrio {
   JOB_RAW_PRIO_PRIVILEGE,
   JOB_RAW_PRIO_HIGH,
   JOB_RAW_PRIO_ORDINARY,
   JOB_RAW_PRIO_LOW,
